### ISSUE TITLE
Was not able to run client.py

### ISSUE THREAD

**Issue by minnaau** [insidesherpa/bank-mergeCoTechTask1#223]
This Traceback error shows up when I try to run client.py

Traceback (most recent call last):
  File "client.py", line 39, in <module>
    quotes = json.loads(urllib2.urlopen(QUERY.format(random.random())).read())
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by startlingmind** [comment]
![image](https://user-images.githubusercontent.com/68396415/90487161-b39c7100-e157-11ea-95d7-0a2c55a59d85.png)

![image](https://user-images.githubusercontent.com/68396415/90487203-c3b45080-e157-11ea-8bcd-8a18c5c1acca.png)

Unable to proceed.

**Comment by onyicecily** [comment]
I have the same error

**Comment by anjali-segu** [comment]
As do I
