### ISSUE TITLE
Python 2.7.16 (default, Jul 13 2019, 16:01:51) [GCC 8.3.0] on linux2

### ISSUE THREAD

**Issue by mohamed2222** [insidesherpa/bank-mergeCoTechTask1#260]
Traceback (most recent call last):
  File "/tmp/upm292031355/bare-imports.py", line 14, in <module>
    ".", extra_ignore_dirs=sys.argv[1].split()
  File "/tmp/upm292031355/pipreqs.py", line 98, in get_all_imports
    missing_modules = imports.keys() - (set(candidates) & imports.keys())
TypeError: unsupported operand type(s) for &: 'set' and 'list'
exit status 1

**Comment by SuyedDalvi** [comment]
I am getting this error as well.
