### ISSUE TITLE
Problems with task 1

### ISSUE THREAD

**Issue by AmanSunda** [insidesherpa/bank-mergeCoTechTask1#270]
Hi all,

When I clicked run after I had done what I needed to I got this error message:

Traceback (most recent call last):
  File "client3.py", line 34, in <module>
    quotes = json.loads(urllib.request.urlopen(QUERY.format(random.random())).read())
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
 
KeyboardInterrupt

Does anyone know what this means? 

Here's a screenshot of my current code:
![image](https://user-images.githubusercontent.com/90040365/131995870-853347b6-7e8a-4e4c-bd1a-2db7d6b50023.png)

**Comment by abhiram2504** [comment]
Not sure, get he same problem as well!
