### ISSUE TITLE
Client.py issue

### ISSUE THREAD

**Issue by iamlocked** [insidesherpa/bank-mergeCoTechTask1#68]
C:\Users\S\JPMC-tech-task-1>python client.py
Traceback (most recent call last):
  File "client.py", line 52, in <module>
    quotes = json.loads(urllib2.urlopen(QUERY.format(random.random())).read())
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>

**Comment by Ademaove** [comment]
open it in regular cmd. Not in the administrative one. Hope it helps)
